Repository iDrogba/WeatherApp, pull requests merged in 2022-07, with the labels that each got.

#2 Main view add new place modal
  WeatherApp/WeatherApp/Controllers/MainViewController.swift
  WeatherApp/WeatherApp/Views/MainCollectionViewCell.swift
Labels: feature

#9 Add search logic
  WeatherApp/WeatherApp.xcodeproj/project.pbxproj
  WeatherApp/WeatherApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/서핑1.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/서핑1.imageset/서핑.png
  WeatherApp/WeatherApp/Assets.xcassets/서핑2.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/서핑2.imageset/서핑2.png
  WeatherApp/WeatherApp/Assets.xcassets/서핑3.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/서핑3.imageset/서핑3.png
  WeatherApp/WeatherApp/Controllers/MainViewController.swift
  WeatherApp/WeatherApp/Models/RegionalDataModel.swift
  WeatherApp/WeatherApp/Models/WeatherForecastModel.swift
  WeatherApp/WeatherApp/Networking/APIRequest.swift
  WeatherApp/WeatherApp/Views/MainCollectionViewCell.swift
  WeatherApp/WeatherApp/Views/SearchTableViewCell.swift
Labels: feature

#15 Configure main collection view cell
  WeatherApp/WeatherApp.xcodeproj/project.pbxproj
  WeatherApp/WeatherApp/Assets.xcassets/card/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/card/cloudy.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/card/cloudy.imageset/cloudy.png
  WeatherApp/WeatherApp/Assets.xcassets/card/cloudyWithIcon.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/card/cloudyWithIcon.imageset/cloudyWithIcon.png
  WeatherApp/WeatherApp/Assets.xcassets/card/rainy.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/card/rainy.imageset/rainy.png
  WeatherApp/WeatherApp/Assets.xcassets/card/rainyWithIcon.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/card/rainyWithIcon.imageset/rainyWithIcon.png
  WeatherApp/WeatherApp/Assets.xcassets/card/snow.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/card/snow.imageset/snow.png
  WeatherApp/WeatherApp/Assets.xcassets/card/snowWithIcon.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/card/snowWithIcon.imageset/snowWithIcon.png
  WeatherApp/WeatherApp/Assets.xcassets/card/sunny.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/card/sunny.imageset/sunny.png
  WeatherApp/WeatherApp/Assets.xcassets/card/sunnyWithIcon.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/card/sunnyWithIcon.imageset/sunnyWithIcon.png
  WeatherApp/WeatherApp/Assets.xcassets/full/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/full/cloudyFull.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/full/cloudyFull.imageset/cloudyFull.png
  WeatherApp/WeatherApp/Assets.xcassets/full/cloudyWithIconFull.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/full/cloudyWithIconFull.imageset/cloudyWithIconFull.png
  WeatherApp/WeatherApp/Assets.xcassets/full/rainyFull.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/full/rainyFull.imageset/rainyFull.png
  WeatherApp/WeatherApp/Assets.xcassets/full/rainyWithIconFull.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/full/rainyWithIconFull.imageset/rainyWithIconFull.png
  WeatherApp/WeatherApp/Assets.xcassets/full/snowFull.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/full/snowFull.imageset/snowFull.png
  WeatherApp/WeatherApp/Assets.xcassets/full/snowWithIconFull.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/full/snowWithIconFull.imageset/snowWithIconFull.png
  WeatherApp/WeatherApp/Assets.xcassets/full/sunnyFull.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/full/sunnyFull.imageset/sunnyFull.png
  WeatherApp/WeatherApp/Assets.xcassets/full/sunnyWithIconFull.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/full/sunnyWithIconFull.imageset/sunnyWithIconFull.png
  WeatherApp/WeatherApp/Assets.xcassets/surf1.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/surf1.imageset/surf1.png
  WeatherApp/WeatherApp/Assets.xcassets/surf2.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/surf2.imageset/surf3.png
  WeatherApp/WeatherApp/Assets.xcassets/surf3.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/surf3.imageset/surf2.png
  WeatherApp/WeatherApp/Assets.xcassets/surf4.imageset/Contents.json
  WeatherApp/WeatherApp/Assets.xcassets/surf4.imageset/surf4.png
  WeatherApp/WeatherApp/Controllers/MainViewController.swift
  WeatherApp/WeatherApp/Info.plist
  WeatherApp/WeatherApp/Models/RegionalDataModel.swift
  WeatherApp/WeatherApp/Models/WeatherForecastModel.swift
  WeatherApp/WeatherApp/Networking/APIRequest.swift
  WeatherApp/WeatherApp/SceneDelegate.swift
  WeatherApp/WeatherApp/Util/Extensions.swift
  WeatherApp/WeatherApp/ViewModels/MainViewModel.swift
  WeatherApp/WeatherApp/Views/MainCollectionViewCell.swift
  WeatherApp/WeatherApp/Views/SearchTableViewCell.swift
Labels: bug, feature

#14 #13 RegionWeatherView-DayCollectionView 구현
  WeatherApp/WeatherApp/Controllers/RegionWeatherViewController.swift
  WeatherApp/WeatherApp/Views/DayWeatherCollectionViewCell.swift
Labels: feature

#18 [FEAT] #17 Region weather view data
  WeatherApp/WeatherApp/Controllers/MainViewController.swift
  WeatherApp/WeatherApp/Controllers/RegionWeatherViewController.swift
  WeatherApp/WeatherApp/Util/CustomColors.swift
  WeatherApp/WeatherApp/Views/DayWeatherCollectionViewCell.swift
  WeatherApp/WeatherApp/Views/WeekWeatherTableViewCell.swift
Labels: feature

#22 Region weather view data
  WeatherApp/WeatherApp.xcodeproj/project.pbxproj
  WeatherApp/WeatherApp/Controllers/MainViewController.swift
  WeatherApp/WeatherApp/Controllers/RegionWeatherViewController.swift
  WeatherApp/WeatherApp/Models/WeekWeather.swift
  WeatherApp/WeatherApp/Views/DayWeatherCollectionViewCell.swift
  WeatherApp/WeatherApp/Views/WeekWeatherTableViewCell.swift
Labels: bug
